### ISSUE TITLE
Would you consider putting up a gh-pages branch?

### ISSUE THREAD

**Issue by davidwesst** [Chrinkus/walk#12]
GitHub provides GitHub Pages for repositories to host a simple site for free on GitHub itself. That way, people could play the latest published version of your game without having to pull the source code down and run it locally.

https://pages.github.com/

For this, you'd want to start a project sites from scratch.

Just a thought.

**Comment by Chrinkus** [comment]
Sounds like a great idea. I've been wondering how I could share this with people other than yourself.
I'd like to get #8 and #9 done first so the project has a little more polish. Would I have to create a new repo or just add a branch?

**Comment by davidwesst** [comment]
You create a new branch named `gh-pages

**Comment by Chrinkus** [comment]
Created gh-pages branch and pushed code to it. Thanks Dave!
